schema_version = "1.0.0"

id = "graph_generator"
version = "1.2.2"
name = "Graph Generator"
tagline = "Generate graph between saved keyframes"
maintainer = "The French Monkey"
license = ["SPDX:GPL-3.0-or-later"]
type = "add-on"
blender_version_min = "4.4.0"
tags = ["Animation"]


website = "https://tfmstyle.com"
report_issues = "https://github.com/TFMSTYLE/Graph_Generator/issues"

